apiVersion: v1
kind: Pod
metadata:
  labels:
    app: httpd-authentication
  name: httpd-authentication
spec:
  containers:
  - name: httpd-authentication
    image: container-registry.dacodastrack.com/fuckyou/httpd-authentication:latest
    command: ["/bin/bash", "-c", "while true; do sleep 10000; done"]
    env:
    - name: PATH
      value: /usr/local/apache2/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
    - name: TERM
      value: xterm
    - name: HOSTNAME
    - name: container
      value: podman
    - name: HTTPD_PREFIX
      value: /usr/local/apache2
    - name: HTTPD_VERSION
      value: 2.4.41
    - name: HTTPD_SHA256
      value: 133d48298fe5315ae9366a0ec66282fa4040efa5d566174481077ade7d18ea40
    - name: HTTPD_PATCHES
    ports:
    - containerPort: 80
      hostPort: 8080
      protocol: TCP
    resources: {}
    workingDir: /usr/local/apache2
  - name: mysql
    image: docker.io/library/mysql:latest
    # command: ["mysqld", "--user", "mysql"]
    # command: ["mysqld"]
    command: ["docker-entrypoint.sh", "mysqld"]
    env:
    - name: PATH
      value: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
    - name: TERM
      value: xterm
    - name: HOSTNAME
    - name: container
      value: podman
    - name: GOSU_VERSION
      value: "1.7"
    - name: MYSQL_MAJOR
      value: "8.0"
    - name: MYSQL_VERSION
      value: 8.0.18-1debian9
    - name: MYSQL_ROOT_PASSWORD
      value: mysqlrootpassword
    ports:
    - containerPort: 3306
      hostPort: 33060
      protocol: TCP
    resources: {}
    securityContext:
      allowPrivilegeEscalation: true
      capabilities: {}
      privileged: false
      readOnlyRootFilesystem: false
    stdin: true
    tty: true
    workingDir: /

