#!/bin/bash

set -ex

# CONTAINER=$(buildah from docker.io/library/ubuntu)
# buildah run "$CONTAINER" /bin/sh -c 'apt-get update && apt-get install -y apache2 libaprutil1-dbd-mysql mysql-client'
CONTAINER=$(buildah from httpd-authentication)
MOUNT=$(buildah mount "$CONTAINER")

rsync -av root/ "$MOUNT/"

buildah run "$CONTAINER" chown -R daemon:daemon /usr/share/apache2/default-site

IMAGE_ID=$(buildah commit "$CONTAINER" httpd-authentication)
